apiVersion: v1
kind: Service
metadata:
  name: {{ include "amazing-people-app.fullname" . }}
  labels:
    {{- include "amazing-people-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 80
      targetPort: http-frontend
      protocol: TCP
      name: http-frontend
  selector:
    {{- include "amazing-people-app.selectorLabels" . | nindent 4 }}
